import { LineEdit, Button, TextEdit, GridBox, ComboBox, HorizontalBox } from "std-widgets.slint";

enum GraphModes {
    Graph_2D,
    Graph_3D,
}

export component DataGraphCreator {

    pure callback csv_with_columns(int) -> [string];

    private property <GraphModes> graph_mode: GraphModes.Graph-3D;
    private property <[string]> mode_names: ["2D", "3D"];
    private property <percent> axis_proportion: 33%;

    GridLayout {
        Row {
            ComboBox {
                current-value: mode_names[1];
                model: mode_names;
                selected(value) => {
                    if value == mode_names[0] {
                        graph_mode = GraphModes.Graph-2D;
                        axis_proportion = 50%;
                    }
                    else if value == mode_names[1] {
                        graph_mode = GraphModes.Graph-3D;
                        axis_proportion = 33%;
                    }
                }
            }

            graph_preview := Image {
                rowspan: 5;
                col: 1;
                source: @image-url("resources/svg/Test.svg");
            }
        }

        Row {
            HorizontalBox {
                title_name := Text {text: "Title: "; vertical-alignment: center;}
                LineEdit {}
            }
        }

        Row {
            HorizontalBox {
                x_axis_name := Text {text: "X-Axis Label: "; vertical-alignment: center;}
                LineEdit {}
            }
        }
        
        Row {
            HorizontalBox {
                y_axis_name := Text {text: "Y-Axis Label: "; vertical-alignment: center;}
                LineEdit {}
            }
        }
 
        Row { 
            HorizontalBox {
                z_axis_name := Text {text: "Z-Axis Label: "; vertical-alignment: center; visible: graph_mode == GraphModes.Graph-3D;}
                LineEdit {visible: graph_mode == GraphModes.Graph-3D;}
            }
        }

        Row {
            Text {
                text: "X Values:";
                width: axis_proportion;
            }
            Text {
                text: "Y Values:";
                width: axis_proportion;
            }
            Text {
                visible: graph_mode == GraphModes.Graph-3D;
                text: "Z Values:";
                width: axis_proportion;
            }
        }

        Row {
        
            x-axis := TextEdit {
                min-height: 100px;
                width: 33%;
            }

            y-axis := TextEdit {
                min-height: 100px;
                width: 33%;
            }

            z-axis := TextEdit {
                min-height: 100px;
                width: 33%;
            }
        }

        Row {
            Button {
                text: "From CSV";
                clicked => {
                    if graph_mode == GraphModes.Graph-2D {
                        fill_columns(csv_with_columns(2));
                    }
                    else if graph_mode == GraphModes.Graph-3D {
                        fill_columns(csv_with_columns(3));
                    }
                    
                }
            }

            Button {
                text: "Create and Show Graph";
            }
        }
    }

    function fill_columns(columns: [string]) {
        if columns.length == 2 {
            x-axis.text = columns[0];
            y-axis.text = columns[1];
        
        }
        else if columns.length == 3 {
            x-axis.text = columns[0];
            y-axis.text = columns[1];
            z-axis.text = columns[2];
        }
    }
}