
import { LineEdit, TextEdit, HorizontalBox, VerticalBox, Button, Switch } from "std-widgets.slint";
export component ExpressionCalculator {
    pure callback calculate_expression(string) -> string;
    pure callback append_history(string, string, string) -> string;
    pure callback clear_history();

    private property <bool> history_hidden: false;

    VerticalBox { 
        HorizontalBox {
            Text {
                text: "Infix: ";
                vertical-alignment: center;
            }
            expression_space :=  LineEdit {
                placeholder-text: "Type A Math Expression Here";
            }
            Text {
                vertical-alignment: center;
                text: "=";
            }
            answer_space := LineEdit {
                read-only: true;
            }
            Button {
                text: "✔";
                clicked => {
                    answer-space.text = calculate_expression(expression-space.text);
                    calc-history.text = append_history(calc-history.text, expression-space.text, answer-space.text);
                }
            }
        }

        VerticalBox {
            HorizontalBox {
                Text {
                    text: "History";
                    font-size: 24px;
                }
                Button {
                    text: "Clear History";
                    clicked => {
                        clear_history();
                        calc-history.text = "";
                    }
                }
                Text {
                    text: "Show History:";
                    vertical-alignment: center;
                }
                Switch {
                    checked: true;
                    toggled => {
                        history_hidden = !self.checked;
                        if history_hidden {
                            calc-history.min-height = 0;
                        }
                        else {
                            calc-history.min-height = 100px;
                        }
                    }
                }
            }
            calc_history := TextEdit {
                min-height: 100px;
                visible: !history_hidden;
            }
        }
    }
}