
import { HorizontalBox, VerticalBox, TextEdit, ComboBox, Button, LineEdit } from "std-widgets.slint";

export component StatsCalc {

    pure callback data_from_csv() -> string;
    pure callback one_dimensional_statistics(string) -> string;

    HorizontalBox {
        VerticalBox {
            input_window := TextEdit {
                min-height: 200px;
            }
            from_file_button := Button {
                text: "From CSV";
                clicked => {
                    input-window.text = data_from_csv();
                }
            }
        }
        
        VerticalBox {
            output_window := TextEdit {
                read-only: true;
                min-height: 200px;
            }
            stat_op_console := GridLayout {
                one_d_stats_button := Button {
                    text: "1D Stats";
                    clicked => {
                        output-window.text = one_dimensional_statistics(input-window.text);
                    }
                }
            }
        }
    }
}